//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viisaus_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Time { get; set; }
        public string Message { get; set; }
        public Nullable<int> Upvote { get; set; }
        public Nullable<int> Downvote { get; set; }
        public string Emoijtag { get; set; }
    
        public virtual User User { get; set; }
    }
}
